### PR TITLE
refactor: split the logic in different files

### PR DESCRIPTION
**Pull request by Kelvur**
I think this refactor improves the readability and maintenance

### CODE REVIEW

**Comment by Kelvur** [comment]
I will add linter rules when `eslint-config-k14v` is ready

**Comment by Kelvur** [comment]
I rebase the branch to the last changes in `develop` #4.

But the test files sometimes, not always
image

I will try to fix that

**Comment by rubeniskov** [comment]
@Kelvur Few months ago I made a different approach of this module for manage one of my own packages, but more condensed and less madness. if you want to checkout to see if is valid for implement or get some pieces of code to cleanup the current code if you want it.

```javascript
#!/usr/bin/env node

const path = require('path');
const fs = require('fs');
const { promisify } = require('util');

const writeFile = promisify(fs.writeFile);
const glob = promisify(require('glob'));

const mkdirp = promisify(fs.mkdir);
const rimraf = promisify(require('rimraf'));

const main = async (argv) => {
  const argDir = argv[1] || 'src';
  const cwdDir = process.cwd();
  const scanDir = path.join(cwdDir, argDir);
  const cleanFlag = argv.includes('--clean');
  const expose = argv.find((_, idx, _argv) => _argv[idx - 1] === '--expose');

  const files = await glob('{*.js,**/*.js}', {
    // Restrict scan directory
    cwd: scanDir,
    // Retrieve relative paths
    absolute: false,
    // Ignore files that it being used in local only by its sibling
    ignore: '**/*.{spec,test,stories}.js',
  });

  const rootFiles = files
    .map((file) => file.split(path.sep)[0])
    .filter((file, index, self) => self.indexOf(file) === index && file !== '.');

  process.stderr.write(`${files.length} Files detected!\n`);

  if (cleanFlag) {
    const filesToRemove = rootFiles.filter((file) => fs.existsSync(file));
    await Promise.all(filesToRemove.map((file) => rimraf(file)));
    process.stderr.write(`${filesToRemove.length} Files cleaned!\n`);
  } else {
    const dirsToCreate = files
      .map((file) => path.dirname(file))
      .filter((file, index, self) => self.indexOf(file) === index && file !== '.')
      .filter((file) => fs.lstatSync(path.resolve(cwdDir, argDir, file)).isDirectory())
      .filter((file) => !fs.existsSync(file));
    await Promise.all(dirsToCreate.map((file) => mkdirp(file, { recursive: true })));
    if (dirsToCreate.length) {
      process.stderr.write(`${dirsToCreate.length} Directories created!\n`);
    }
    await Promise.all(files.map((file) => {
      const relPath = path.relative(path.dirname(path.join(cwdDir, file)), path.join(argDir, file)).replace(/\\/gi, '/');
      const moduleExport = `module.exports = require('./${relPath}')${expose ? `.${expose}` : ''};\n`;

      return writeFile(path.join(cwdDir, file), moduleExport);
    }));
    if (files.length) {
      process.stderr.write(`${files.length} Files linked!\n`);
    }
  }
};

main(process.argv.slice(1));
```

**Comment by Kelvur** [comment]
> @Kelvur Few months ago I made a different approach of this module for manage one of my own packages, but more condensed and less madness. if you want to checkout to see if is valid for implement or get some pieces of code to cleanup the current code if you want it.
> 
> ```js
> #!/usr/bin/env node
> 
> const path = require('path');
> const fs = require('fs');
> const { promisify } = require('util');
> 
> const writeFile = promisify(fs.writeFile);
> const glob = promisify(require('glob'));
> 
> const mkdirp = promisify(fs.mkdir);
> const rimraf = promisify(require('rimraf'));
> 
> const main = async (argv) => {
>   const argDir = argv[1] || 'src';
>   const cwdDir = process.cwd();
>   const scanDir = path.join(cwdDir, argDir);
>   const cleanFlag = argv.includes('--clean');
>   const expose = argv.find((_, idx, _argv) => _argv[idx - 1] === '--expose');
> 
>   const files = await glob('{*.js,**/*.js}', {
>     // Restrict scan directory
>     cwd: scanDir,
>     // Retrieve relative paths
>     absolute: false,
>     // Ignore files that it being used in local only by its sibling
>     ignore: '**/*.{spec,test,stories}.js',
>   });
> 
>   const rootFiles = files
>     .map((file) => file.split(path.sep)[0])
>     .filter((file, index, self) => self.indexOf(file) === index && file !== '.');
> 
>   process.stderr.write(`${files.length} Files detected!\n`);
> 
>   if (cleanFlag) {
>     const filesToRemove = rootFiles.filter((file) => fs.existsSync(file));
>     await Promise.all(filesToRemove.map((file) => rimraf(file)));
>     process.stderr.write(`${filesToRemove.length} Files cleaned!\n`);
>   } else {
>     const dirsToCreate = files
>       .map((file) => path.dirname(file))
>       .filter((file, index, self) => self.indexOf(file) === index && file !== '.')
>       .filter((file) => fs.lstatSync(path.resolve(cwdDir, argDir, file)).isDirectory())
>       .filter((file) => !fs.existsSync(file));
>     await Promise.all(dirsToCreate.map((file) => mkdirp(file, { recursive: true })));
>     if (dirsToCreate.length) {
>       process.stderr.write(`${dirsToCreate.length} Directories created!\n`);
>     }
>     await Promise.all(files.map((file) => {
>       const relPath = path.relative(path.dirname(path.join(cwdDir, file)), path.join(argDir, file)).replace(/\\/gi, '/');
>       const moduleExport = `module.exports = require('./${relPath}')${expose ? `.${expose}` : ''};\n`;
> 
>       return writeFile(path.join(cwdDir, file), moduleExport);
>     }));
>     if (files.length) {
>       process.stderr.write(`${files.length} Files linked!\n`);
>     }
>   }
> };
> 
> main(process.argv.slice(1));
> ```

The code is similar, Did you mean is easier to read thanks to async/await?

I prefer keep this library, has test and with this refactor the code is easier to be read and other little things (I can improve the reading process with async/await in other branch)

**Pull request merged**
